FROM python:3.12.7-slim-bullseye

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install pipenv
RUN pip install --no-cache-dir pipenv

# Copy the Pipfile from the web folder
COPY services/web/Pipfile services/web/Pipfile.lock* /app/

# Install dependencies system-wide (so Django runs normally)
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy --system

# Copy the Django project
COPY services/web/inventory/ /app/inventory/

WORKDIR /app/services/web/inventory

# Django app
EXPOSE 8000

# Minio
EXPOSE 9001

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
