# Generated by Django 5.2.6 on 2025-10-21 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='VasquesEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('fuel', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Alcohol', 'Alcohol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Flex', 'Flex')], max_length=50)),
                ('autonomy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('exhaust_emission_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('subcategory', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('rounds_panel', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vasques_emissions', to='rounds.roundspanel')),
                ('urban_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vasques_emissions', to='vasques_standard.urbanconsumption')),
            ],
        ),
    ]
