# Generated by Django 5.2.6 on 2025-10-21 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRFStandardEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Alcohol', 'Alcohol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Flex', 'Flex')], max_length=50)),
                ('fraction', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mileage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('subcategory', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('rounds_panel', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrf_standard_emissions', to='rounds.roundspanel')),
            ],
        ),
    ]
