# Generated by Django 5.2.6 on 2025-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WRFRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Completed'), (4, 'Error')], default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('output_file_path', models.CharField(max_length=255)),
                ('namelist', models.TextField()),
            ],
        ),
    ]
