# Generated by Django 5.2.6 on 2025-10-21 12:58

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoundsPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WRFRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Completed'), (4, 'Error')], default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('output_file_path', models.CharField(max_length=255)),
                ('namelist', models.JSONField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rounds.roundspanel')),
            ],
            managers=[
                ('queue', django.db.models.manager.Manager()),
            ],
        ),
    ]
