# Generated by Django 5.2.6 on 2025-12-16 13:13

import rounds.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrfround',
            name='netcdf',
            field=models.FileField(null=True, storage=rounds.storage.NetCDFMinioStorage(), upload_to='round_outputs/'),
        ),
    ]
